import type { GetServerSideProps, NextPage } from 'next';
import { useRouter } from 'next/dist/client/router';
import Head from 'next/head';
import { Button } from '@material-ui/core';
import { useState } from 'react';
import Swal from 'sweetalert2';
import ModalForm from '../components/modal'
import { Status } from '../models/enum/status';
import { Raffle } from '../models/raffle';
import { getRaffles, saveRaffles } from '../utils/raffle';
import Image from 'next/image';
import CESD1 from '../assets/img/CESD1.jpg';
import CESD2 from '../assets/img/CESD2.jpg';
import CESD3 from '../assets/img/CESD3.jpg';
import CESD4 from '../assets/img/CESD4.jpg';
import CESD5 from '../assets/img/CESD5.jpg';
import CESD6 from '../assets/img/CESD6.jpg';
import Pix from '../assets/img/Pix.jpg';
import LogoVentureiros from '../assets/img/LogoVentureiros.png';

interface HomeInterface {
  data: Status[];
}

const Home = (props: HomeInterface) => {

  const [data, setData] = useState<Status[]>(props.data);
  const [select, setSelect] = useState<Raffle>({ numbers: [] });
  const [modalIsOpen, setIsOpen] = useState(false);
  const [isLoading, setLoading] = useState(false);
  const router = useRouter()

  function closeModal() {
    setIsOpen(false);
  }

  const save = async ({ name, email }: any) => {
    if (select.numbers.length == 0) {
      return Swal.fire(
        'Algo deu errado',
        'Você deve selecionar um número antes!',
        'error'
      )
    }
    select.email = email;
    select.name = name;
    select.status = Status.reserved;
    try {
      setLoading(true);
      await saveRaffles(select);
      router.push('/obrigado')
    } catch (error) {
      return Swal.fire(
        'Algo deu errado',
        `${error ?? ''}`,
        'error'
      )
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className='container'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <div className="container-logo">
          <div className="logo-imagem">
            <Image
              src={LogoVentureiros}
              layout='fixed'
              objectFit='contain'
              width={200}
              height={60}
            />
          </div>
        </div>

        <div className="menu">
          <ul>
            <li><a href="#numero">Números</a></li>
            <li><a href="#">Pagamentos</a></li>
            <li><a href="#">Como Funciona</a></li>
            <li><a href="#">FAQ</a></li>
          </ul>
        </div>
      </header>

      <div className="img">
        <section className="galeria">
          <Image
            src={CESD1}
            layout='fill'
            objectFit='contain'
          />
          <Image
            src={CESD2}
            layout='fill'
            objectFit='contain'
          />
          <Image
            src={CESD3}
            layout='fill'
            objectFit='contain'
          />
          <Image
            src={CESD4}
            layout='fill'
            objectFit='contain'
          />
        </section>

        <div className="texto">
          <h1 className="titulo">Vale presente no valor de 150 reais</h1>
          <p className="sub">O CESD está montando uma rifa online em parceria com o
            Protagonistas do Futuro <br /> a fim de arrecadar verba
            para compra de computadores para o programa Estimulação Precoce. <br />
            Se identificou e quer nos ajudar nessa conquista?
            Participe agora!</p><br />
          <p>Sorteio p/ <b>Direto com o Organizador</b></p>
        </div>
      </div>
      <div className="status">
        <button className="status-btn todos">Todos</button>
        <button className="valor">1 Número por <b>R$ 10</b></button>
        <button className="status-btn disponiveis">Disponíveis</button>
        <button className="status-btn reservados">Reservados</button>
        <button className="status-btn pagos">Pagos</button>

      </div>

      <main className='main'>
        <div className='numbers'>

          {
            data.map((number, index) => {
              return (
                <div
                  key={Math.random()}
                  className={
                    `number ${number} ${select?.numbers.find(item => item == index + 1) && 'selected'}`
                  }
                  onClick={() => {
                    let se = select;
                    const indexx = select?.numbers.findIndex(item => item == index + 1);
                    console.log(select?.numbers.find(item => item == index + 1))
                    if (number == Status.available && indexx == -1) {

                      setSelect({ ...select, numbers: [...select!.numbers, index + 1] });
                    }
                    if (indexx != -1) {
                      se?.numbers.splice(indexx ?? 0, 1);
                      setSelect({ ...se });
                    }

                  }}
                >
                  {index + 1}
                </div>
              )
            })
          }

        </div>

        <div className='select'>
          <div >
            <p>Total</p>
            <p><strong>R$ {select!.numbers.length * 10},00</strong></p>
          </div>
          <Button
            onClick={() => {
              if (!select.numbers.length) {
                return Swal.fire(
                  'Algo deu errado',
                  'Você deve selecionar um número antes!',
                  'error'
                )
              }
              setIsOpen(true)
            }}
            variant="outlined">
            Reservar
          </Button>

        </div>

      </main>
      <ModalForm
        modalIsOpen={modalIsOpen}
        isLoading={isLoading}
        closeModal={() => {

          closeModal()
        }}
        save={({ name, email }: any) => save({ name, email })}
      />
      <div className="forpag">
        <div>
          <h1 className="pag">Forma de Pagamento</h1>
        </div>
        <div>
          <hr className="product-line" />
          <div>
            <Image
              src={Pix}
              layout='fixed'
              width={200}
              height={200}
              className="piximg"
              objectFit='contain'
            />
          </div>
          <div>
            <h2 className="pix">Pix: (19) 97118-9340</h2>
          </div>
          <a className="comprovante"
            href="https://web.whatsapp.com/send?phone=5519971189340"
            target="_blank">Enviar
            Comprovante</a>
        </div>
      </div>

    </div>
  )
}

export default Home;

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const numbers = Array.from(Array(100).keys());
  const arrays: Status[] = [];

  const raffles = async () => {
    const result: Raffle[] = await getRaffles();
    if (result) {
      result.forEach(element => {
        if (element.numbers) {
          element.numbers.forEach(number => {
            arrays[number - 1] = element.status!;
          })
        }
      });
      numbers.forEach((item, index) => {
        arrays[index] = arrays[index] ?? Status.available;
      })
    }

  }

  await raffles();

  return {
    props: {
      data: arrays
    }
  }

}
